<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
		<string>inc</string>
	</array>
	<key>name</key>
	<string>Merlin Assembler</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comment</string>
			<key>match</key>
			<string>^[*;](.)*</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comment</string>
			<key>match</key>
			<string>[\s][;](.)*</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Registers</string>
			<key>match</key>
			<string>,(a|x|y|A|X|Y)\b</string>
			<key>name</key>
			<string>storage.register</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Value</string>
			<key>match</key>
			<string>[\#?[<|>|^|$|%]|$|\\][a-zA-Z0-9_\-+/*:\\]*</string>
			<key>name</key>
			<string>constant.numeric.asm</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>String</string>
			<key>match</key>
			<string>"[^"]*"</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>String</string>
			<key>match</key>
			<string>'[^']*'</string>
			<key>name</key>
			<string>string.quoted.single</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>String</string>
			<key>match</key>
			<string>\b(org|dsk|sav|lnk|typ|rel|dum|dend|chk|dat|err|asm|sna|aux|ent|ext|xpl|ali|knd|bsz|mac|eom|put|putbin|use|mx|ORG|DSK|SAV|LNK|TYP|REL|DUM|DEND|CHK|DAT|ERR|ASM|SNA|AUX|ENT|EXT|XPL|ALI|KND|BSZ|MAC|EOM|PUT|PUTBIN|USE|MX)\b</string>
			<key>name</key>
			<string>entity.name.function.preprocessor</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Label Reference</string>
			<key>match</key>
			<string>\b(BCC|BLT|BCS|BGE|BEQ|BIT|BMI|BNE|BPL|BRA|BRK|BRL|BVC|BVS|JMP|JML|JSR|JSL|bcc|blt|bcs|bge|beq|bit|bmi|bne|bpl|bra|brk|brl|bvc|bvs|jmp|jml|jsr|jsl)\b[\s]+([a-zA-Z0-9_:\]]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>Label Reference</string>
			<key>match</key>
			<string>\b(HEX|DFB|DB|DDB|DA|DW|ADR|ADRL|DS|ASC|DCI|INV|FLS|REV|STR|STRL|hex|dfb|db|ddb|da|dw|adr|adrl|ds|asc|dci|inv|fls|rev|str|strl)\b[\s]+([#$a-zA-Z0-9_:+*/"'\-\]\.!\&,]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>Label Reference</string>
			<key>match</key>
			<string>\b(ADC|ADCL|AND|ANDL|ASL|CMP|CMPL|CPX|CPY|DEC|DEX|DEY|EOR|INC|INX|INY|LDA|LDAL|LDX|LDY|LSR|ORA|ROL|ROR|SBC|STA|STAL|STX|STY|STZ|adc|adcl|and|andl|asl|cmp|cmpl|cpx|cpy|dec|dex|dey|eor|inc|inx|iny|lda|ldal|ldx|ldy|lsr|ora|rol|ror|sbc|sta|stal|stx|sty|stz)\b[\s]+([a-zA-Z0-9_:\]]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.mnemonic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>Label Reference ZP</string>
			<key>match</key>
			<string>\b(ADC|ADCL|AND|ANDL|ASL|CMP|CMPL|CPX|CPY|DEC|DEX|DEY|EOR|INC|INX|INY|LDA|LDAL|LDX|LDY|LSR|ORA|ROL|ROR|SBC|STA|STAL|STX|STY|STZ|adc|adcl|and|andl|asl|cmp|cmpl|cpx|cpy|dec|dex|dey|eor|inc|inx|iny|lda|ldal|ldx|ldy|lsr|ora|rol|ror|sbc|sta|stal|stx|sty|stz)\b[\s]+([\[(][$:a-zA-Z0-9_]+[\])])</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.mnemonic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.variable</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>Mnemonics</string>
			<key>match</key>
			<string>\b(adc|and|asl|bcc|bcs|beq|bit|bmi|bne|bpl|bra|brk|brl|bvc|bvs|clc|cld|cli|clv|cmp|cpx|cpy|cop|dc|dec|dex|dey|eor|inc|inx|iny|jmp|jml|jsr|jsl|lda|ldx|ldy|lsr|mvn|mvp|nop|ora|pea|pei|per|pha|phb|phd|phk|php|phx|phy|pla|plb|pld|plp|plx|ply|rep|rol|ror|rti|rts|rtl|sbc|sec|sed|sei|sep|sta|stx|sty|stp|stz|tax|tay|tcd|tcs|tdc|tdc|tdx|txa|txs|txy|tya|tyx|trb|tsb|wai|wdm|xba|xce|ADC|AND|ASL|BCC|BCS|BEQ|BIT|BMI|BNE|BPL|BRA|BRK|BRL|BVC|BVS|CLC|CLD|CLI|CLV|CMP|CPX|CPY|COP|DC|DEC|DEX|DEY|EOR|INC|INX|INY|JMP|JML|JSR|JSL|LDA|LDX|LDY|LSR|MVN|MVP|NOP|ORA|PEA|PEI|PER|PHA|PHB|PHD|PHK|PHP|PHX|PHY|PLA|PLB|PLD|PLP|PLX|PLY|REP|ROL|ROR|RTI|RTS|RTL|SBC|SEC|SED|SEI|SEP|STA|STX|STY|STP|STZ|TAX|TAY|TCD|TCS|TDC|TDC|TDX|TXA|TXS|TXY|TYA|TYX|TRB|TSB|WAI|WDM|XBA|XCE)(.[b|w|v])?\b</string>
			<key>name</key>
			<string>keyword.mnemonic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Label</string>
			<key>match</key>
			<string>^([a-zA-Z0-9_:\]]+)\s</string>
			<key>name</key>
			<string>string.label</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.asm.65816</string>
	<key>uuid</key>
	<string>3dd8d751-4598-463e-ac06-194e5a314394</string>
</dict>
</plist>
